<a href="https://colab.research.google.com/github/hxri/Deep-Learning-Lab/blob/main/Experiment_2_Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

#Models
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB

#datasets
from sklearn.datasets import load_wine

In [ ]:
#Datasets
from sklearn.datasets import load_wine

In [ ]:
#models
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB

In [ ]:
data = load_wine()

In [ ]:
data['data']

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [ ]:
data['feature_names']

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [ ]:
data['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [ ]:
data['target_names']

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [ ]:
X = data['data']
y = data['target']

In [ ]:
classifiers = [GaussianNB(), BernoulliNB(binarize = 5.0), MultinomialNB()]

## Wine Dataset

In [ ]:
def train(classifiers, X, y, split):

  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=split, random_state=42)

  print("Data dimensions\n")
  print("Train Data :", str(X_train.shape) + " and " + str(y_train.shape))
  print("Test Data :", str(X_test.shape) + " and " + str(y_test.shape))
  print("--------------------\n\n")
  
  for i in range(len(classifiers)):
    print(str(classifiers[i]))
    print("\n")
    classifiers[i].fit(X_train, y_train)
    y_pred = classifiers[i].predict(X_test)
    print(y_pred)
    print("\n")
    print(classification_report(y_test, y_pred))
    print("--------------------\n\n")

In [ ]:
train(classifiers, X, y, 0.10)

Data dimensions

Train Data : (160, 13) and (160,)
Test Data : (18, 13) and (18,)
--------------------


GaussianNB()


[0 0 2 0 1 0 1 2 1 2 0 2 0 1 0 1 1 1]


              precision    recall  f1-score   support

     class_0       1.00      1.00      1.00         7
     class_1       1.00      1.00      1.00         7
     class_2       1.00      1.00      1.00         4

    accuracy                           1.00        18
   macro avg       1.00      1.00      1.00        18
weighted avg       1.00      1.00      1.00        18

--------------------


BernoulliNB(binarize=5.0)


[0 0 1 0 1 0 1 0 1 0 1 0 1 1 0 1 1 1]


              precision    recall  f1-score   support

     class_0       0.62      0.71      0.67         7
     class_1       0.70      1.00      0.82         7
     class_2       0.00      0.00      0.00         4

    accuracy                           0.67        18
   macro avg       0.44      0.57      0.50        18
weighted avg       0.52      0.67      0.5

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Heart Disease Dataset

In [ ]:
data2 = pd.read_csv('/content/heart_2020_cleaned.csv')

In [ ]:
data2

HeartDisease    BMI Smoking AlcoholDrinking Stroke  PhysicalHealth  \
0                No  16.60     Yes              No     No             3.0   
1                No  20.34      No              No    Yes             0.0   
2                No  26.58     Yes              No     No            20.0   
3                No  24.21      No              No     No             0.0   
4                No  23.71      No              No     No            28.0   
...             ...    ...     ...             ...    ...             ...   
319790          Yes  27.41     Yes              No     No             7.0   
319791           No  29.84     Yes              No     No             0.0   
319792           No  24.24      No              No     No             0.0   
319793           No  32.81      No              No     No             0.0   
319794           No  46.56      No              No     No             0.0   

        MentalHealth DiffWalking     Sex  AgeCategory      Race Diabetic  \
0               30.0          No  Female        55-59     White      Yes   
1                0.0          No  Female  80 or older     White       No   
2               30.0          No    Male        65-69     White      Yes   
3                0.0          No  Female        75-79     White       No   
4                0.0         Yes  Female        40-44     White       No   
...              ...         ...     ...          ...       ...      ...   
319790           0.0         Yes    Male        60-64  Hispanic      Yes   
319791           0.0          No    Male        35-39  Hispanic       No   
319792           0.0          No  Female        45-49  Hispanic       No   
319793           0.0          No  Female        25-29  Hispanic       No   
319794           0.0          No  Female  80 or older  Hispanic       No   

       PhysicalActivity  GenHealth  SleepTime Asthma KidneyDisease SkinCancer  
0                   Yes  Very good        5.0    Yes            No        Yes  
1                   Yes  Very good        7.0     No            No         No  
2                   Yes       Fair        8.0    Yes            No         No  
3                    No       Good        6.0     No            No        Yes  
4                   Yes  Very good        8.0     No            No         No  
...                 ...        ...        ...    ...           ...        ...  
319790               No       Fair        6.0    Yes            No         No  
319791              Yes  Very good        5.0    Yes            No         No  
319792              Yes       Good        6.0     No            No         No  
319793               No       Good       12.0     No            No         No  
319794              Yes       Good        8.0     No            No         No  

[319795 rows x 18 columns]

In [ ]:
columns = ['HeartDisease', 'Smoking',	'AlcoholDrinking',	'Stroke',	'DiffWalking',	'Sex',	'AgeCategory',	'Race',	'Diabetic',	'PhysicalActivity',	'GenHealth',	'Asthma',	'KidneyDisease',	'SkinCancer']

In [ ]:
stacked = data2[columns].stack()
data2[columns] = pd.Series(stacked.factorize()[0], index=stacked.index).unstack()

In [ ]:
data2

HeartDisease    BMI  Smoking  AlcoholDrinking  Stroke  PhysicalHealth  \
0                  0  16.60        1                0       0             3.0   
1                  0  20.34        0                0       1             0.0   
2                  0  26.58        1                0       0            20.0   
3                  0  24.21        0                0       0             0.0   
4                  0  23.71        0                0       0            28.0   
...              ...    ...      ...              ...     ...             ...   
319790             1  27.41        1                0       0             7.0   
319791             0  29.84        1                0       0             0.0   
319792             0  24.24        0                0       0             0.0   
319793             0  32.81        0                0       0             0.0   
319794             0  46.56        0                0       0             0.0   

        MentalHealth  DiffWalking  Sex  AgeCategory  Race  Diabetic  \
0               30.0            0    2            3     4         1   
1                0.0            0    2            6     4         0   
2               30.0            0    7            8     4         1   
3                0.0            0    2           10     4         0   
4                0.0            1    2           12     4         0   
...              ...          ...  ...          ...   ...       ...   
319790           0.0            1    7           16    26         1   
319791           0.0            0    7           25    26         0   
319792           0.0            0    2           20    26         0   
319793           0.0            0    2           29    26         0   
319794           0.0            0    2            6    26         0   

        PhysicalActivity  GenHealth  SleepTime  Asthma  KidneyDisease  \
0                      1          5        5.0       1              0   
1                      1          5        7.0       0              0   
2                      1          9        8.0       1              0   
3                      0         11        6.0       0              0   
4                      1          5        8.0       0              0   
...                  ...        ...        ...     ...            ...   
319790                 0          9        6.0       1              0   
319791                 1          5        5.0       1              0   
319792                 1         11        6.0       0              0   
319793                 0         11       12.0       0              0   
319794                 1         11        8.0       0              0   

        SkinCancer  
0                1  
1                0  
2                0  
3                1  
4                0  
...            ...  
319790           0  
319791           0  
319792           0  
319793           0  
319794           0  

[319795 rows x 18 columns]

In [ ]:
X = data2.loc[:, data2.columns != 'HeartDisease']

In [ ]:
X = X.values

In [ ]:
y = data2['HeartDisease'].values

In [ ]:
train(classifiers, X, y, 0.10)

Data dimensions

Train Data : (287815, 17) and (287815,)
Test Data : (31980, 17) and (31980,)
--------------------


GaussianNB()


[0 0 0 ... 0 0 0]


              precision    recall  f1-score   support

           0       0.94      0.89      0.91     29112
           1       0.27      0.41      0.32      2868

    accuracy                           0.85     31980
   macro avg       0.60      0.65      0.62     31980
weighted avg       0.88      0.85      0.86     31980

--------------------


BernoulliNB(binarize=5.0)


[0 0 0 ... 0 0 0]


              precision    recall  f1-score   support

           0       0.91      1.00      0.95     29112
           1       0.00      0.00      0.00      2868

    accuracy                           0.91     31980
   macro avg       0.46      0.50      0.48     31980
weighted avg       0.83      0.91      0.87     31980

--------------------


MultinomialNB()


[0 0 0 ... 0 0 0]




/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           0       0.93      0.87      0.90     29112
           1       0.22      0.36      0.27      2868

    accuracy                           0.83     31980
   macro avg       0.58      0.62      0.59     31980
weighted avg       0.87      0.83      0.85     31980

--------------------


